type PortalDictionary = Record<string, string>;

const nb: PortalDictionary = {
  'adminPortal.title':'Administratorportal','adminPortal.signedInAs':'Innlogget som','adminPortal.administrator':'Administrator','adminPortal.loadingOrganization':'Henter organisasjonen din...','adminPortal.loadOrganizationError':'Kunne ikke hente organisasjonen.','adminPortal.noOrganization':'Ingen organisasjonstilknytning',
  'adminPortal.nav.dashboard':'Dashboard','adminPortal.nav.members':'Medlemmer','adminPortal.nav.news':'Nyheter','adminPortal.nav.activities':'Aktiviteter','adminPortal.nav.notifications':'Varslinger','adminPortal.nav.board':'Styret','adminPortal.nav.access':'Tilgang','adminPortal.nav.settings':'Innstillinger',
  'adminPortal.dashboard.welcome':'Velkommen til','adminPortal.dashboard.overview':'Her ser du en oppdatert oversikt over organisasjonen.','adminPortal.dashboard.statsError':'Kunne ikke hente all statistikk:','adminPortal.dashboard.members':'Medlemmer','adminPortal.dashboard.news':'Nyheter','adminPortal.dashboard.upcomingActivities':'Kommende aktiviteter','adminPortal.dashboard.activeBoardMembers':'Aktive styremedlemmer','adminPortal.dashboard.quickActions':'Hurtigvalg','adminPortal.dashboard.editNews':'Opprett eller rediger nyhet','adminPortal.dashboard.editActivity':'Opprett eller rediger aktivitet','adminPortal.dashboard.manageAccess':'Administrer tilgang og invitasjonskoder','adminPortal.dashboard.updateSettings':'Oppdater organisasjonsinnstillinger',
  'adminPortal.trial.title':'7 dagers gratis prøveperiode','adminPortal.trial.day':'dag','adminPortal.trial.days':'dager','adminPortal.trial.remaining':'igjen','adminPortal.trial.expires':'utløper','adminPortal.trial.noCharge':'Ingen betaling gjennomføres før betalingsløsningen er valgt og aktivert.','adminPortal.trial.expiredTitle':'Prøveperioden er utløpt','adminPortal.trial.expiredBody':'Dataene er beholdt. Innholdsproduksjon og utsending er midlertidig låst til abonnementet aktiveres.'
};

const en: PortalDictionary = {
  'adminPortal.title':'Administrator portal','adminPortal.signedInAs':'Signed in as','adminPortal.administrator':'Administrator','adminPortal.loadingOrganization':'Loading your organization...','adminPortal.loadOrganizationError':'The organization could not be loaded.','adminPortal.noOrganization':'No organization connection',
  'adminPortal.nav.dashboard':'Dashboard','adminPortal.nav.members':'Members','adminPortal.nav.news':'News','adminPortal.nav.activities':'Activities','adminPortal.nav.notifications':'Notifications','adminPortal.nav.board':'Board','adminPortal.nav.access':'Access','adminPortal.nav.settings':'Settings',
  'adminPortal.dashboard.welcome':'Welcome to','adminPortal.dashboard.overview':'Here is an updated overview of the organization.','adminPortal.dashboard.statsError':'Some statistics could not be loaded:','adminPortal.dashboard.members':'Members','adminPortal.dashboard.news':'News','adminPortal.dashboard.upcomingActivities':'Upcoming activities','adminPortal.dashboard.activeBoardMembers':'Active board members','adminPortal.dashboard.quickActions':'Quick actions','adminPortal.dashboard.editNews':'Create or edit news','adminPortal.dashboard.editActivity':'Create or edit an activity','adminPortal.dashboard.manageAccess':'Manage access and invitation codes','adminPortal.dashboard.updateSettings':'Update organization settings',
  'adminPortal.trial.title':'7-day free trial','adminPortal.trial.day':'day','adminPortal.trial.days':'days','adminPortal.trial.remaining':'remaining','adminPortal.trial.expires':'expires','adminPortal.trial.noCharge':'No payment is made until a payment solution is selected and activated.','adminPortal.trial.expiredTitle':'The trial has expired','adminPortal.trial.expiredBody':'Your data is retained. Publishing and sending are temporarily locked until the subscription is activated.'
};

const tr: PortalDictionary = {
  'adminPortal.title':'Yönetici Portalı','adminPortal.signedInAs':'Giriş yapan','adminPortal.administrator':'Yönetici','adminPortal.loadingOrganization':'Kuruluşunuz yükleniyor...','adminPortal.loadOrganizationError':'Kuruluş yüklenemedi.','adminPortal.noOrganization':'Kuruluş bağlantısı bulunamadı',
  'adminPortal.nav.dashboard':'Kontrol Paneli','adminPortal.nav.members':'Üyeler','adminPortal.nav.news':'Haberler','adminPortal.nav.activities':'Etkinlikler','adminPortal.nav.notifications':'Bildirimler','adminPortal.nav.board':'Yönetim Kurulu','adminPortal.nav.access':'Erişim','adminPortal.nav.settings':'Ayarlar',
  'adminPortal.dashboard.welcome':'Hoş geldiniz','adminPortal.dashboard.overview':'Kuruluşun güncel genel görünümünü burada görebilirsiniz.','adminPortal.dashboard.statsError':'Bazı istatistikler yüklenemedi:','adminPortal.dashboard.members':'Üyeler','adminPortal.dashboard.news':'Haberler','adminPortal.dashboard.upcomingActivities':'Yaklaşan etkinlikler','adminPortal.dashboard.activeBoardMembers':'Aktif yönetim kurulu üyeleri','adminPortal.dashboard.quickActions':'Hızlı işlemler','adminPortal.dashboard.editNews':'Haber oluştur veya düzenle','adminPortal.dashboard.editActivity':'Etkinlik oluştur veya düzenle','adminPortal.dashboard.manageAccess':'Erişim ve davet kodlarını yönet','adminPortal.dashboard.updateSettings':'Kuruluş ayarlarını güncelle',
  'adminPortal.trial.title':'7 günlük ücretsiz deneme','adminPortal.trial.day':'gün','adminPortal.trial.days':'gün','adminPortal.trial.remaining':'kaldı','adminPortal.trial.expires':'sona erme','adminPortal.trial.noCharge':'Ödeme çözümü seçilip etkinleştirilene kadar ödeme alınmaz.','adminPortal.trial.expiredTitle':'Deneme süresi sona erdi','adminPortal.trial.expiredBody':'Verileriniz korunur. Abonelik etkinleştirilene kadar içerik yayınlama ve gönderme geçici olarak kilitlidir.'
};

const ar: PortalDictionary = {
  'adminPortal.title':'بوابة المسؤول','adminPortal.signedInAs':'تم تسجيل الدخول باسم','adminPortal.administrator':'المسؤول','adminPortal.loadingOrganization':'جارٍ تحميل مؤسستك...','adminPortal.loadOrganizationError':'تعذر تحميل المؤسسة.','adminPortal.noOrganization':'لا يوجد ارتباط بمؤسسة',
  'adminPortal.nav.dashboard':'لوحة التحكم','adminPortal.nav.members':'الأعضاء','adminPortal.nav.news':'الأخبار','adminPortal.nav.activities':'الأنشطة','adminPortal.nav.notifications':'الإشعارات','adminPortal.nav.board':'مجلس الإدارة','adminPortal.nav.access':'الوصول','adminPortal.nav.settings':'الإعدادات',
  'adminPortal.dashboard.welcome':'مرحباً بك في','adminPortal.dashboard.overview':'هنا يمكنك رؤية نظرة محدثة عن المؤسسة.','adminPortal.dashboard.statsError':'تعذر تحميل بعض الإحصاءات:','adminPortal.dashboard.members':'الأعضاء','adminPortal.dashboard.news':'الأخبار','adminPortal.dashboard.upcomingActivities':'الأنشطة القادمة','adminPortal.dashboard.activeBoardMembers':'أعضاء مجلس الإدارة النشطون','adminPortal.dashboard.quickActions':'إجراءات سريعة','adminPortal.dashboard.editNews':'إنشاء خبر أو تعديله','adminPortal.dashboard.editActivity':'إنشاء نشاط أو تعديله','adminPortal.dashboard.manageAccess':'إدارة الوصول ورموز الدعوة','adminPortal.dashboard.updateSettings':'تحديث إعدادات المؤسسة',
  'adminPortal.trial.title':'تجربة مجانية لمدة 7 أيام','adminPortal.trial.day':'يوم','adminPortal.trial.days':'أيام','adminPortal.trial.remaining':'متبقية','adminPortal.trial.expires':'تنتهي في','adminPortal.trial.noCharge':'لن يتم تحصيل أي مبلغ قبل اختيار حل الدفع وتفعيله.','adminPortal.trial.expiredTitle':'انتهت الفترة التجريبية','adminPortal.trial.expiredBody':'تم الاحتفاظ ببياناتك. النشر والإرسال مقفلان مؤقتاً حتى يتم تفعيل الاشتراك.'
};

const ur: PortalDictionary = {
  'adminPortal.title':'ایڈمن پورٹل','adminPortal.signedInAs':'لاگ اِن بطور','adminPortal.administrator':'ایڈمن','adminPortal.loadingOrganization':'آپ کی تنظیم لوڈ ہو رہی ہے...','adminPortal.loadOrganizationError':'تنظیم لوڈ نہیں ہو سکی۔','adminPortal.noOrganization':'تنظیم سے کوئی تعلق نہیں ملا',
  'adminPortal.nav.dashboard':'ڈیش بورڈ','adminPortal.nav.members':'ارکان','adminPortal.nav.news':'خبریں','adminPortal.nav.activities':'سرگرمیاں','adminPortal.nav.notifications':'اطلاعات','adminPortal.nav.board':'بورڈ','adminPortal.nav.access':'رسائی','adminPortal.nav.settings':'ترتیبات',
  'adminPortal.dashboard.welcome':'خوش آمدید','adminPortal.dashboard.overview':'یہاں تنظیم کا تازہ خلاصہ دیکھا جا سکتا ہے۔','adminPortal.dashboard.statsError':'کچھ اعداد و شمار لوڈ نہیں ہو سکے:','adminPortal.dashboard.members':'ارکان','adminPortal.dashboard.news':'خبریں','adminPortal.dashboard.upcomingActivities':'آنے والی سرگرمیاں','adminPortal.dashboard.activeBoardMembers':'فعال بورڈ ارکان','adminPortal.dashboard.quickActions':'فوری اقدامات','adminPortal.dashboard.editNews':'خبر بنائیں یا ترمیم کریں','adminPortal.dashboard.editActivity':'سرگرمی بنائیں یا ترمیم کریں','adminPortal.dashboard.manageAccess':'رسائی اور دعوتی کوڈز کا انتظام','adminPortal.dashboard.updateSettings':'تنظیم کی ترتیبات اپ ڈیٹ کریں',
  'adminPortal.trial.title':'7 دن کی مفت آزمائش','adminPortal.trial.day':'دن','adminPortal.trial.days':'دن','adminPortal.trial.remaining':'باقی','adminPortal.trial.expires':'اختتام','adminPortal.trial.noCharge':'ادائیگی کا طریقہ منتخب اور فعال ہونے تک کوئی رقم وصول نہیں کی جائے گی۔','adminPortal.trial.expiredTitle':'آزمائشی مدت ختم ہو گئی','adminPortal.trial.expiredBody':'آپ کا ڈیٹا محفوظ ہے۔ رکنیت فعال ہونے تک اشاعت اور ترسیل عارضی طور پر بند ہے۔'
};

const dictionaries: Record<string, PortalDictionary> = { nb, en, tr, ar, ur };

export function getAdminPortalTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key];
}
