type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'news.pushFallback':'En ny nyhet er publisert i appen.','news.pushTitlePrefix':'Nyhet: ','news.supabaseMissing':'Supabase er ikke konfigurert.','news.tableMissing':'Nyhetstabellen er ikke klar i Supabase ennå.','news.titleRequired':'Tittel er obligatorisk.','news.saveFailed':'Nyheten kunne ikke lagres.','news.deleteConfirmPrefix':'Slette nyheten «','news.deleteConfirmSuffix':'»?','news.deleteFailed':'Nyheten kunne ikke slettes: ','news.pushResent':'Push-varselet ble sendt på nytt.','news.pushFailed':'Push-varselet kunne ikke sendes.',
  'news.coreModule':'Kjernemodul','news.title':'Nyheter','news.countSuffix':'nyheter i organisasjonen.','news.new':'Ny nyhet','news.search':'Søk i nyheter','news.allStatuses':'Alle statuser','news.published':'Publisert','news.draft':'Utkast','news.loading':'Henter nyheter...','news.loadFailedTitle':'Nyhetsmodulen kan ikke laste data','news.empty':'Ingen nyheter funnet','news.noSummary':'Ingen sammendrag','news.edit':'Rediger','news.delete':'Slett','news.pushAgain':'Push igjen','news.editTitle':'Rediger nyhet','news.formTitle':'Tittel','news.summary':'Sammendrag','news.content':'Innhold','news.imageUrl':'Bilde-URL','news.status':'Status','news.sendPush':'Send push-varsel','news.pushEditHelp':'Av som standard ved redigering. Slå på bare når du ønsker nytt varsel.','news.pushCreateHelp':'Slå av dersom nyheten skal lagres uten varsel.','news.saving':'Lagrer...','news.saveChanges':'Lagre endringer','news.create':'Opprett nyhet','news.close':'Lukk'
};
const en: Dictionary = {
  'news.pushFallback':'A new news item has been published in the app.','news.pushTitlePrefix':'News: ','news.supabaseMissing':'Supabase is not configured.','news.tableMissing':'The news table is not ready in Supabase yet.','news.titleRequired':'Title is required.','news.saveFailed':'The news item could not be saved.','news.deleteConfirmPrefix':'Delete the news item “','news.deleteConfirmSuffix':'”?','news.deleteFailed':'The news item could not be deleted: ','news.pushResent':'The push notification was sent again.','news.pushFailed':'The push notification could not be sent.',
  'news.coreModule':'Core module','news.title':'News','news.countSuffix':'news items in the organization.','news.new':'New news item','news.search':'Search news','news.allStatuses':'All statuses','news.published':'Published','news.draft':'Draft','news.loading':'Loading news...','news.loadFailedTitle':'The news module cannot load data','news.empty':'No news found','news.noSummary':'No summary','news.edit':'Edit','news.delete':'Delete','news.pushAgain':'Push again','news.editTitle':'Edit news','news.formTitle':'Title','news.summary':'Summary','news.content':'Content','news.imageUrl':'Image URL','news.status':'Status','news.sendPush':'Send push notification','news.pushEditHelp':'Off by default when editing. Turn it on only when you want a new notification.','news.pushCreateHelp':'Turn it off if the news item should be saved without a notification.','news.saving':'Saving...','news.saveChanges':'Save changes','news.create':'Create news item','news.close':'Close'
};
const tr: Dictionary = {
  'news.pushFallback':'Uygulamada yeni bir haber yayınlandı.','news.pushTitlePrefix':'Haber: ','news.supabaseMissing':'Supabase yapılandırılmamış.','news.tableMissing':'Haber tablosu Supabase’de henüz hazır değil.','news.titleRequired':'Başlık zorunludur.','news.saveFailed':'Haber kaydedilemedi.','news.deleteConfirmPrefix':'“','news.deleteConfirmSuffix':'” haberini silmek istiyor musunuz?','news.deleteFailed':'Haber silinemedi: ','news.pushResent':'Push bildirimi yeniden gönderildi.','news.pushFailed':'Push bildirimi gönderilemedi.',
  'news.coreModule':'Temel modül','news.title':'Haberler','news.countSuffix':'haber kayıtlı.','news.new':'Yeni haber','news.search':'Haberlerde ara','news.allStatuses':'Tüm durumlar','news.published':'Yayınlandı','news.draft':'Taslak','news.loading':'Haberler yükleniyor...','news.loadFailedTitle':'Haber modülü verileri yükleyemiyor','news.empty':'Haber bulunamadı','news.noSummary':'Özet yok','news.edit':'Düzenle','news.delete':'Sil','news.pushAgain':'Push tekrar','news.editTitle':'Haberi düzenle','news.formTitle':'Başlık','news.summary':'Özet','news.content':'İçerik','news.imageUrl':'Görsel URL','news.status':'Durum','news.sendPush':'Push bildirimi gönder','news.pushEditHelp':'Düzenlemede varsayılan olarak kapalıdır. Yalnızca yeni bildirim göndermek istediğinizde açın.','news.pushCreateHelp':'Haber bildirim olmadan kaydedilecekse kapatın.','news.saving':'Kaydediliyor...','news.saveChanges':'Değişiklikleri kaydet','news.create':'Haber oluştur','news.close':'Kapat'
};
const ar: Dictionary = {
  'news.pushFallback':'تم نشر خبر جديد في التطبيق.','news.pushTitlePrefix':'خبر: ','news.supabaseMissing':'لم يتم إعداد Supabase.','news.tableMissing':'جدول الأخبار غير جاهز في Supabase بعد.','news.titleRequired':'العنوان مطلوب.','news.saveFailed':'تعذر حفظ الخبر.','news.deleteConfirmPrefix':'هل تريد حذف الخبر «','news.deleteConfirmSuffix':'»؟','news.deleteFailed':'تعذر حذف الخبر: ','news.pushResent':'تم إرسال الإشعار مرة أخرى.','news.pushFailed':'تعذر إرسال الإشعار.',
  'news.coreModule':'وحدة أساسية','news.title':'الأخبار','news.countSuffix':'أخبار في المؤسسة.','news.new':'خبر جديد','news.search':'البحث في الأخبار','news.allStatuses':'كل الحالات','news.published':'منشور','news.draft':'مسودة','news.loading':'جارٍ تحميل الأخبار...','news.loadFailedTitle':'تعذر تحميل بيانات وحدة الأخبار','news.empty':'لم يتم العثور على أخبار','news.noSummary':'لا يوجد ملخص','news.edit':'تعديل','news.delete':'حذف','news.pushAgain':'إرسال الإشعار مجدداً','news.editTitle':'تعديل الخبر','news.formTitle':'العنوان','news.summary':'الملخص','news.content':'المحتوى','news.imageUrl':'رابط الصورة','news.status':'الحالة','news.sendPush':'إرسال إشعار','news.pushEditHelp':'مغلق افتراضياً عند التعديل. فعّله فقط عند الرغبة في إرسال إشعار جديد.','news.pushCreateHelp':'أوقفه إذا أردت حفظ الخبر دون إشعار.','news.saving':'جارٍ الحفظ...','news.saveChanges':'حفظ التغييرات','news.create':'إنشاء الخبر','news.close':'إغلاق'
};
const ur: Dictionary = {
  'news.pushFallback':'ایپ میں نئی خبر شائع ہوئی ہے۔','news.pushTitlePrefix':'خبر: ','news.supabaseMissing':'Supabase ترتیب نہیں دیا گیا۔','news.tableMissing':'خبروں کی جدول Supabase میں ابھی تیار نہیں۔','news.titleRequired':'عنوان ضروری ہے۔','news.saveFailed':'خبر محفوظ نہیں ہو سکی۔','news.deleteConfirmPrefix':'کیا خبر “','news.deleteConfirmSuffix':'” حذف کرنی ہے؟','news.deleteFailed':'خبر حذف نہیں ہو سکی: ','news.pushResent':'پش اطلاع دوبارہ بھیج دی گئی۔','news.pushFailed':'پش اطلاع نہیں بھیجی جا سکی۔',
  'news.coreModule':'بنیادی ماڈیول','news.title':'خبریں','news.countSuffix':'خبریں تنظیم میں۔','news.new':'نئی خبر','news.search':'خبروں میں تلاش','news.allStatuses':'تمام حالتیں','news.published':'شائع شدہ','news.draft':'مسودہ','news.loading':'خبریں لوڈ ہو رہی ہیں...','news.loadFailedTitle':'خبروں کا ماڈیول ڈیٹا لوڈ نہیں کر سکا','news.empty':'کوئی خبر نہیں ملی','news.noSummary':'خلاصہ نہیں','news.edit':'ترمیم','news.delete':'حذف','news.pushAgain':'پش دوبارہ','news.editTitle':'خبر میں ترمیم','news.formTitle':'عنوان','news.summary':'خلاصہ','news.content':'مواد','news.imageUrl':'تصویر کا URL','news.status':'حالت','news.sendPush':'پش اطلاع بھیجیں','news.pushEditHelp':'ترمیم کے وقت بطور ڈیفالٹ بند ہے۔ نئی اطلاع کے لیے اسے فعال کریں۔','news.pushCreateHelp':'خبر بغیر اطلاع کے محفوظ کرنی ہو تو اسے بند کریں۔','news.saving':'محفوظ ہو رہا ہے...','news.saveChanges':'تبدیلیاں محفوظ کریں','news.create':'خبر بنائیں','news.close':'بند کریں'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getNewsTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
