type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'public.loading':'Henter organisasjonen...','public.loadError':'Den offentlige organisasjonssiden kunne ikke lastes.','public.about':'Om organisasjonen','public.follow':'Følg oss','public.website':'Nettside','public.contact':'Kontakt','public.openingHours':'Åpningstider','public.weeklyEvent':'Ukentlig arrangement','public.news':'Nyheter','public.noNews':'Ingen offentlige nyheter er publisert ennå.','public.activities':'Kommende aktiviteter','public.noActivities':'Ingen offentlige aktiviteter er planlagt.','public.team':'Styret og kontaktpersoner','public.noTeam':'Ingen offentlige kontaktpersoner er lagt til.','public.donate':'Støtt organisasjonen','public.donateNumber':'Donasjonsnummer','public.bankAccount':'Bankkonto','public.openDonation':'Åpne donasjon','public.map':'Åpne kart','public.email':'Send e-post','public.call':'Ring','public.published':'Publisert','public.location':'Sted','public.readMore':'Les mer','public.noDescription':'Ingen beskrivelse er lagt til.'
};
const en: Dictionary = {
  'public.loading':'Loading the organization...','public.loadError':'The public organization page could not be loaded.','public.about':'About the organization','public.follow':'Follow us','public.website':'Website','public.contact':'Contact','public.openingHours':'Opening hours','public.weeklyEvent':'Weekly event','public.news':'News','public.noNews':'No public news has been published yet.','public.activities':'Upcoming activities','public.noActivities':'No public activities are planned.','public.team':'Board and contacts','public.noTeam':'No public contacts have been added.','public.donate':'Support the organization','public.donateNumber':'Donation number','public.bankAccount':'Bank account','public.openDonation':'Open donation','public.map':'Open map','public.email':'Send email','public.call':'Call','public.published':'Published','public.location':'Location','public.readMore':'Read more','public.noDescription':'No description has been added.'
};
const tr: Dictionary = {
  'public.loading':'Kuruluş yükleniyor...','public.loadError':'Kuruluşun herkese açık sayfası yüklenemedi.','public.about':'Kuruluş hakkında','public.follow':'Bizi takip edin','public.website':'Web sitesi','public.contact':'İletişim','public.openingHours':'Çalışma saatleri','public.weeklyEvent':'Haftalık etkinlik','public.news':'Haberler','public.noNews':'Henüz herkese açık haber yayınlanmadı.','public.activities':'Yaklaşan etkinlikler','public.noActivities':'Planlanmış herkese açık etkinlik yok.','public.team':'Yönetim kurulu ve iletişim kişileri','public.noTeam':'Herkese açık iletişim kişisi eklenmedi.','public.donate':'Kuruluşu destekleyin','public.donateNumber':'Bağış numarası','public.bankAccount':'Banka hesabı','public.openDonation':'Bağışı aç','public.map':'Haritayı aç','public.email':'E-posta gönder','public.call':'Ara','public.published':'Yayınlandı','public.location':'Konum','public.readMore':'Devamını oku','public.noDescription':'Açıklama eklenmedi.'
};
const ar: Dictionary = {
  'public.loading':'جارٍ تحميل المؤسسة...','public.loadError':'تعذر تحميل الصفحة العامة للمؤسسة.','public.about':'عن المؤسسة','public.follow':'تابعنا','public.website':'الموقع الإلكتروني','public.contact':'الاتصال','public.openingHours':'ساعات العمل','public.weeklyEvent':'الفعالية الأسبوعية','public.news':'الأخبار','public.noNews':'لم يتم نشر أخبار عامة بعد.','public.activities':'الأنشطة القادمة','public.noActivities':'لا توجد أنشطة عامة مخططة.','public.team':'مجلس الإدارة وجهات الاتصال','public.noTeam':'لم تتم إضافة جهات اتصال عامة.','public.donate':'ادعم المؤسسة','public.donateNumber':'رقم التبرع','public.bankAccount':'الحساب البنكي','public.openDonation':'فتح التبرع','public.map':'فتح الخريطة','public.email':'إرسال بريد','public.call':'اتصال','public.published':'منشور','public.location':'الموقع','public.readMore':'اقرأ المزيد','public.noDescription':'لم تتم إضافة وصف.'
};
const ur: Dictionary = {
  'public.loading':'تنظیم لوڈ ہو رہی ہے...','public.loadError':'تنظیم کا عوامی صفحہ لوڈ نہیں ہو سکا۔','public.about':'تنظیم کے بارے میں','public.follow':'ہمیں فالو کریں','public.website':'ویب سائٹ','public.contact':'رابطہ','public.openingHours':'اوقات کار','public.weeklyEvent':'ہفتہ وار پروگرام','public.news':'خبریں','public.noNews':'ابھی کوئی عوامی خبر شائع نہیں ہوئی۔','public.activities':'آنے والی سرگرمیاں','public.noActivities':'کوئی عوامی سرگرمی طے نہیں۔','public.team':'بورڈ اور رابطہ افراد','public.noTeam':'کوئی عوامی رابطہ شخص شامل نہیں۔','public.donate':'تنظیم کی مدد کریں','public.donateNumber':'عطیہ نمبر','public.bankAccount':'بینک اکاؤنٹ','public.openDonation':'عطیہ کھولیں','public.map':'نقشہ کھولیں','public.email':'ای میل بھیجیں','public.call':'کال','public.published':'شائع شدہ','public.location':'مقام','public.readMore':'مزید پڑھیں','public.noDescription':'کوئی تفصیل شامل نہیں۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getPublicOrganizationTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
