type Dictionary = Record<string, string>;

const nb: Dictionary = {
  'staff.organization':'Organisasjon','staff.title':'Styret og ledelsen','staff.countSuffix':'registrerte personer','staff.add':'Legg til','staff.hidden':'Skjult','staff.noRole':'Ingen rolle','staff.edit':'Rediger person','staff.new':'Ny person','staff.name':'Navn','staff.position':'Rolle/stilling','staff.bio':'Kort beskrivelse (valgfritt)','staff.image':'Bilde (valgfritt)','staff.uploading':'Laster opp...','staff.chooseImage':'Velg bilde','staff.removeImage':'Fjern','staff.phone':'Telefon','staff.email':'E-post','staff.whatsapp':'Eget WhatsApp-nummer (valgfritt)','staff.contactOptions':'Kontaktmuligheter','staff.contactHelp':'Bare valgte kontaktmetoder vises på personens side.','staff.call':'Ring','staff.sms':'SMS','staff.showPublic':'Vis personen offentlig i appen','staff.active':'Aktiv','staff.saveChanges':'Lagre endringer','staff.create':'Opprett','staff.close':'Lukk','staff.chooseImageFile':'Velg en bildefil.','staff.imageTooLarge':'Bildet kan ikke være større enn 5 MB.','staff.deletePrefix':'Slette ','staff.deleteSuffix':'?','staff.orderSaveFailed':'Rekkefølgen kunne ikke lagres.'
};
const en: Dictionary = {
  'staff.organization':'Organization','staff.title':'Board and management','staff.countSuffix':'registered people','staff.add':'Add','staff.hidden':'Hidden','staff.noRole':'No role','staff.edit':'Edit person','staff.new':'New person','staff.name':'Name','staff.position':'Role/position','staff.bio':'Short description (optional)','staff.image':'Image (optional)','staff.uploading':'Uploading...','staff.chooseImage':'Choose image','staff.removeImage':'Remove','staff.phone':'Phone','staff.email':'Email','staff.whatsapp':'Separate WhatsApp number (optional)','staff.contactOptions':'Contact options','staff.contactHelp':'Only selected contact methods are shown on the person’s page.','staff.call':'Call','staff.sms':'SMS','staff.showPublic':'Show this person publicly in the app','staff.active':'Active','staff.saveChanges':'Save changes','staff.create':'Create','staff.close':'Close','staff.chooseImageFile':'Choose an image file.','staff.imageTooLarge':'The image cannot be larger than 5 MB.','staff.deletePrefix':'Delete ','staff.deleteSuffix':'?','staff.orderSaveFailed':'The order could not be saved.'
};
const tr: Dictionary = {
  'staff.organization':'Kuruluş','staff.title':'Yönetim kurulu ve ekip','staff.countSuffix':'kayıtlı kişi','staff.add':'Ekle','staff.hidden':'Gizli','staff.noRole':'Rol yok','staff.edit':'Kişiyi düzenle','staff.new':'Yeni kişi','staff.name':'Ad','staff.position':'Rol/pozisyon','staff.bio':'Kısa açıklama (isteğe bağlı)','staff.image':'Görsel (isteğe bağlı)','staff.uploading':'Yükleniyor...','staff.chooseImage':'Görsel seç','staff.removeImage':'Kaldır','staff.phone':'Telefon','staff.email':'E-posta','staff.whatsapp':'Ayrı WhatsApp numarası (isteğe bağlı)','staff.contactOptions':'İletişim seçenekleri','staff.contactHelp':'Kişinin sayfasında yalnızca seçilen iletişim yöntemleri gösterilir.','staff.call':'Ara','staff.sms':'SMS','staff.showPublic':'Kişiyi uygulamada herkese açık göster','staff.active':'Aktif','staff.saveChanges':'Değişiklikleri kaydet','staff.create':'Oluştur','staff.close':'Kapat','staff.chooseImageFile':'Bir görsel dosyası seçin.','staff.imageTooLarge':'Görsel 5 MB’den büyük olamaz.','staff.deletePrefix':'Sil: ','staff.deleteSuffix':'?','staff.orderSaveFailed':'Sıralama kaydedilemedi.'
};
const ar: Dictionary = {
  'staff.organization':'المؤسسة','staff.title':'مجلس الإدارة والإدارة','staff.countSuffix':'أشخاص مسجلون','staff.add':'إضافة','staff.hidden':'مخفي','staff.noRole':'بدون دور','staff.edit':'تعديل الشخص','staff.new':'شخص جديد','staff.name':'الاسم','staff.position':'الدور/المنصب','staff.bio':'وصف قصير (اختياري)','staff.image':'الصورة (اختياري)','staff.uploading':'جارٍ الرفع...','staff.chooseImage':'اختر صورة','staff.removeImage':'إزالة','staff.phone':'الهاتف','staff.email':'البريد الإلكتروني','staff.whatsapp':'رقم واتساب منفصل (اختياري)','staff.contactOptions':'خيارات الاتصال','staff.contactHelp':'تظهر فقط طرق الاتصال المحددة في صفحة الشخص.','staff.call':'اتصال','staff.sms':'رسالة نصية','staff.showPublic':'إظهار الشخص للعامة في التطبيق','staff.active':'نشط','staff.saveChanges':'حفظ التغييرات','staff.create':'إنشاء','staff.close':'إغلاق','staff.chooseImageFile':'اختر ملف صورة.','staff.imageTooLarge':'يجب ألا يتجاوز حجم الصورة 5 ميجابايت.','staff.deletePrefix':'حذف ','staff.deleteSuffix':'؟','staff.orderSaveFailed':'تعذر حفظ الترتيب.'
};
const ur: Dictionary = {
  'staff.organization':'تنظیم','staff.title':'بورڈ اور انتظامیہ','staff.countSuffix':'رجسٹرڈ افراد','staff.add':'شامل کریں','staff.hidden':'پوشیدہ','staff.noRole':'کوئی کردار نہیں','staff.edit':'شخص میں ترمیم','staff.new':'نیا شخص','staff.name':'نام','staff.position':'کردار/عہدہ','staff.bio':'مختصر تفصیل (اختیاری)','staff.image':'تصویر (اختیاری)','staff.uploading':'اپ لوڈ ہو رہا ہے...','staff.chooseImage':'تصویر منتخب کریں','staff.removeImage':'ہٹائیں','staff.phone':'فون','staff.email':'ای میل','staff.whatsapp':'علیحدہ WhatsApp نمبر (اختیاری)','staff.contactOptions':'رابطے کے طریقے','staff.contactHelp':'صرف منتخب رابطہ طریقے شخص کے صفحے پر دکھائے جاتے ہیں۔','staff.call':'کال','staff.sms':'ایس ایم ایس','staff.showPublic':'شخص کو ایپ میں عوامی طور پر دکھائیں','staff.active':'فعال','staff.saveChanges':'تبدیلیاں محفوظ کریں','staff.create':'بنائیں','staff.close':'بند کریں','staff.chooseImageFile':'تصویر کی فائل منتخب کریں۔','staff.imageTooLarge':'تصویر 5 MB سے بڑی نہیں ہو سکتی۔','staff.deletePrefix':'حذف کریں ','staff.deleteSuffix':'؟','staff.orderSaveFailed':'ترتیب محفوظ نہیں ہو سکی۔'
};

const dictionaries: Record<string, Dictionary> = { nb, en, tr, ar, ur };
export function getStaffTranslation(language: string, key: string) {
  return dictionaries[language]?.[key] || en[key] || nb[key] || key;
}
