import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const allowedOrigins = new Set(["https://yasaflow.com", "https://yasaflow.vercel.app", "https://test.yasaflow.com"]);
const safeOrigin = (value?: string) => { try { const url = new URL(value || ""); return url.protocol === "https:" ? url.origin : ""; } catch { return ""; } };
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c] ?? c));
function headersFor(req: Request) { const origin=req.headers.get("origin")??""; const ok=allowedOrigins.has(origin)||/^https:\/\/[a-z0-9-]+\.yasaflow\.com$/i.test(origin); return {"Access-Control-Allow-Origin":ok?origin:"https://yasaflow.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json","Vary":"Origin","X-Content-Type-Options":"nosniff"}; }
type EventType="received"|"approved"|"rejected";
type EmailPayload={job_id:string;recipient_email:string;recipient_name:string;organization_name:string;reply_to_email:string|null;welcome_message:string|null};

Deno.serve(async(req:Request)=>{
 const headers=headersFor(req); if(req.method==="OPTIONS")return new Response("ok",{headers}); if(req.method!=="POST")return new Response(JSON.stringify({ok:false,error:"Method not allowed"}),{status:405,headers});
 let jobId="";
 try{
  const supabaseUrl=Deno.env.get("SUPABASE_URL"), anonKey=Deno.env.get("SUPABASE_ANON_KEY"), serviceRoleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), resendKey=Deno.env.get("RESEND_API_KEY"), fromEmail=Deno.env.get("MEMBERSHIP_FROM_EMAIL")||"Yasaflow <noreply@yasaflow.com>";
  if(!supabaseUrl||!anonKey||!serviceRoleKey||!resendKey)throw new Error("Missing server configuration");
  const authorization=req.headers.get("authorization")??""; if(!authorization.toLowerCase().startsWith("bearer "))return new Response(JSON.stringify({ok:false,error:"Unauthorized"}),{status:401,headers});
  const userClient=createClient(supabaseUrl,anonKey,{global:{headers:{Authorization:authorization}},auth:{persistSession:false}}), admin=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});
  const {data:userData,error:userError}=await userClient.auth.getUser(); if(userError||!userData.user)return new Response(JSON.stringify({ok:false,error:"Unauthorized"}),{status:401,headers});
  const raw=await req.text(); if(raw.length>4096)return new Response(JSON.stringify({ok:false,error:"Payload too large"}),{status:413,headers});
  let body:{requestId?:string;eventType?:EventType;appUrl?:string}; try{body=JSON.parse(raw);}catch{return new Response(JSON.stringify({ok:false,error:"Invalid request"}),{status:400,headers});}
  const requestId=String(body.requestId??""), eventType=body.eventType; if(!/^[0-9a-f-]{36}$/i.test(requestId)||!eventType||!["received","approved","rejected"].includes(eventType))return new Response(JSON.stringify({ok:false,error:"Invalid request"}),{status:400,headers});
  const {data:requestRow,error:requestError}=await admin.from("organization_membership_requests").select("organization_id,email").eq("id",requestId).maybeSingle(); if(requestError||!requestRow)return new Response(JSON.stringify({ok:false,error:"Not found"}),{status:404,headers});
  const userEmail=(userData.user.email??"").trim().toLowerCase(); let authorized=eventType==="received"&&userEmail!==""&&userEmail===String(requestRow.email??"").trim().toLowerCase();
  if(!authorized){const {data:adminRow}=await admin.from("organization_admins").select("id").eq("organization_id",requestRow.organization_id).eq("user_id",userData.user.id).eq("invitation_status","accepted").in("role",["owner","admin"]).maybeSingle();authorized=Boolean(adminRow);} if(!authorized)return new Response(JSON.stringify({ok:false,error:"Forbidden"}),{status:403,headers});
  const {data,error}=await admin.rpc("prepare_membership_email",{p_request_id:requestId,p_event_type:eventType}); if(error)throw error; const payload=(data?.[0]??null) as EmailPayload|null; if(!payload)return new Response(JSON.stringify({ok:true,skipped:true}),{headers}); jobId=payload.job_id;
  let cardLink=""; if(eventType==="approved"){const {data:membership}=await admin.from("organization_memberships").select("card_token").eq("organization_id",requestRow.organization_id).ilike("email",requestRow.email).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle(); const origin=safeOrigin(body.appUrl)||safeOrigin(Deno.env.get("PUBLIC_APP_URL")); if(membership?.card_token&&origin)cardLink=`${origin}/member-card?token=${encodeURIComponent(String(membership.card_token))}`;}
  const subjects:Record<EventType,string>={received:`Vi har mottatt medlemsforespørselen din – ${payload.organization_name}`,approved:`Medlemskapet ditt er godkjent – ${payload.organization_name}`,rejected:`Oppdatering om medlemsforespørselen din – ${payload.organization_name}`};
  const intros:Record<EventType,string>={received:`Hei ${escapeHtml(payload.recipient_name)},<br><br>Vi har mottatt medlemsforespørselen din. Organisasjonen behandler den og kontakter deg ved behov.`,approved:`Hei ${escapeHtml(payload.recipient_name)},<br><br>Medlemsforespørselen din er godkjent.`,rejected:`Hei ${escapeHtml(payload.recipient_name)},<br><br>Medlemsforespørselen din er dessverre avslått.`};
  const welcome=eventType==="approved"&&payload.welcome_message?`<p>${escapeHtml(payload.welcome_message).replace(/\n/g,"<br>")}</p>`:"", cardButton=cardLink?`<p style="margin:28px 0"><a href="${escapeHtml(cardLink)}" style="display:inline-block;background:#0A8DFF;color:#fff;text-decoration:none;font-weight:700;padding:14px 22px;border-radius:12px">Åpne medlemskortet mitt</a></p><p style="font-size:13px;color:#666">Medlemskortet inneholder din personlige QR-kode. Ikke del lenken offentlig.</p>`:"";
  const html=`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#222"><p>${intros[eventType]}</p>${welcome}${cardButton}<p>Vennlig hilsen<br>${escapeHtml(payload.organization_name)}</p></div>`;
  const textCard=cardLink?`\n\nÅpne medlemskortet ditt: ${cardLink}\nIkke del lenken offentlig.`:"", text=`${intros[eventType].replace(/<br>/g,"\n").replace(/<[^>]+>/g,"")}${payload.welcome_message?`\n\n${payload.welcome_message}`:""}${textCard}\n\nVennlig hilsen\n${payload.organization_name}`;
  const emailResponse=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${resendKey}`,"Content-Type":"application/json"},body:JSON.stringify({from:fromEmail,to:[payload.recipient_email],reply_to:payload.reply_to_email||undefined,subject:subjects[eventType],html,text})}); const emailResult=await emailResponse.json(); if(!emailResponse.ok)throw new Error(emailResult?.message||"Email notification failed");
  const {error:completeError}=await admin.rpc("complete_membership_email",{p_job_id:jobId,p_request_id:requestId,p_event_type:eventType}); if(completeError)throw completeError;
  return new Response(JSON.stringify({ok:true,id:emailResult.id,card_link_included:Boolean(cardLink)}),{headers});
 }catch(error){const message=error instanceof Error?error.message:String(error);console.error("send-membership-email failed",message);try{const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(jobId&&url&&key){const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});await admin.rpc("fail_membership_email",{p_job_id:jobId,p_error:message.slice(0,500)});}}catch{}return new Response(JSON.stringify({ok:false,error:"Could not send membership email"}),{status:400,headers});}
});