import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Check, Copy, KeyRound, Loader2, Plus, ShieldCheck, Trash2, Users } from 'lucide-react';
import { useAppI18n } from '../lib/appI18n';
import { getAccessTranslation } from '../lib/accessTranslations';
import { ContentVisibilityManager } from './ContentVisibilityManager';
import { GroupManagementModule } from './GroupManagementModule';
import { supabase } from '../lib/supabase';

type AccessMode = 'public' | 'mixed' | 'authenticated';
type ApprovalMode = 'automatic' | 'manual';
type Invite = { id:string; code:string; label:string; role:string; approval_mode:string; max_uses:number|null; use_count:number; expires_at:string|null; active:boolean };
const makeCode=()=>`YSF-${Math.random().toString(36).slice(2,6).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;

export function AccessMembershipModule({organizationId}:{organizationId:string}){
  const {language,locale}=useAppI18n();
  const t=(key:string)=>getAccessTranslation(language,key);
  const [accessMode,setAccessMode]=useState<AccessMode>('public');
  const [approvalMode,setApprovalMode]=useState<ApprovalMode>('automatic');
  const [invites,setInvites]=useState<Invite[]>([]);
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [showCreate,setShowCreate]=useState(false);const [groupVersion,setGroupVersion]=useState(0);
  const [form,setForm]=useState({code:makeCode(),label:'',role:'member',approval_mode:'inherit',max_uses:'',expires_at:''});

  const load=async()=>{if(!supabase)return;setLoading(true);setError('');const [orgResult,inviteResult]=await Promise.all([supabase.from('organizations').select('app_access_mode,membership_approval_mode').eq('id',organizationId).maybeSingle(),supabase.from('organization_invitation_codes').select('id,code,label,role,approval_mode,max_uses,use_count,expires_at,active').eq('organization_id',organizationId).order('created_at',{ascending:false})]);if(orgResult.error)setError(orgResult.error.message);else{setAccessMode((orgResult.data?.app_access_mode||'public') as AccessMode);setApprovalMode((orgResult.data?.membership_approval_mode||'automatic') as ApprovalMode);}if(inviteResult.error)setError(inviteResult.error.message);else setInvites((inviteResult.data||[]) as Invite[]);setLoading(false);};
  useEffect(()=>{void load();},[organizationId,language]);
  const saveSettings=async()=>{if(!supabase)return;setSaving(true);setError('');setMessage('');const {error}=await supabase.from('organizations').update({app_access_mode:accessMode,membership_approval_mode:approvalMode,updated_at:new Date().toISOString()}).eq('id',organizationId);setSaving(false);if(error)return setError(error.message);window.dispatchEvent(new Event('yasaflow-organization-settings-changed'));setMessage(t('access.saved'));};
  const createInvite=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setError('');const maxUses=form.max_uses.trim()?Number(form.max_uses):null;const {error}=await supabase.from('organization_invitation_codes').insert({organization_id:organizationId,code:form.code.trim().toUpperCase(),label:form.label.trim()||null,role:form.role,approval_mode:form.approval_mode,max_uses:maxUses,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null,active:true});setSaving(false);if(error)return setError(error.message);setShowCreate(false);setForm({code:makeCode(),label:'',role:'member',approval_mode:'inherit',max_uses:'',expires_at:''});await load();};
  const toggleInvite=async(invite:Invite)=>{if(!supabase)return;await supabase.from('organization_invitation_codes').update({active:!invite.active,updated_at:new Date().toISOString()}).eq('id',invite.id).eq('organization_id',organizationId);await load();};
  const removeInvite=async(invite:Invite)=>{if(!supabase||!confirm(`${t('access.deletePrefix')}${invite.code}${t('access.deleteSuffix')}`))return;await supabase.from('organization_invitation_codes').delete().eq('id',invite.id).eq('organization_id',organizationId);await load();};
  const copy=async(value:string)=>{await navigator.clipboard.writeText(value);setMessage(t('access.copied'));};
  const activeCount=useMemo(()=>invites.filter(i=>i.active).length,[invites]);
  if(loading)return <div className="flex justify-center p-8"><Loader2 className="animate-spin"/></div>;

  const accessOptions=[
    {value:'public' as const,title:t('access.publicTitle'),description:t('access.publicBody')},
    {value:'mixed' as const,title:t('access.mixedTitle'),description:t('access.mixedBody')},
    {value:'authenticated' as const,title:t('access.authTitle'),description:t('access.authBody')},
  ];
  const roleLabel=(role:string)=>role==='resident'?t('access.resident'):role==='volunteer'?t('access.volunteer'):role==='staff'?t('access.staff'):role==='board'?t('access.board'):t('access.member');

  return <div className="space-y-4">
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><ShieldCheck style={{color:'var(--brand-primary)'}}/><div><h3 className="font-serif text-2xl">{t('access.title')}</h3><p className="mt-1 text-sm opacity-55">{t('access.subtitle')}</p></div></div></section>
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h4 className="font-semibold">{t('access.appAccess')}</h4><div className="mt-4 grid gap-3">{accessOptions.map(({value,title,description})=><label key={value} className="flex cursor-pointer items-start gap-3 rounded-2xl border p-4"><input type="radio" name="access" className="mt-1" checked={accessMode===value} onChange={()=>setAccessMode(value)}/><span><span className="block text-sm font-semibold">{title}</span><span className="mt-1 block text-xs leading-5 opacity-55">{description}</span></span></label>)}</div><div className="mt-5"><label className="text-sm font-semibold">{t('access.approval')}</label><select value={approvalMode} onChange={e=>setApprovalMode(e.target.value as ApprovalMode)} className="mt-2 w-full rounded-xl border p-3 text-sm"><option value="automatic">{t('access.autoApproval')}</option><option value="manual">{t('access.manualApproval')}</option></select></div><button onClick={saveSettings} disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-medium disabled:opacity-50" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{saving?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>} {t('access.save')}</button></section>

    <GroupManagementModule organizationId={organizationId} onChanged={()=>setGroupVersion(value=>value+1)}/>
    <ContentVisibilityManager key={groupVersion} organizationId={organizationId}/>

    <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h4 className="font-semibold">{t('access.codes')}</h4><p className="mt-1 text-xs opacity-55">{activeCount} {t('access.activeCodes')}</p></div><button onClick={()=>setShowCreate(true)} className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-medium" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}><Plus size={15}/>{t('access.newCode')}</button></div><div className="mt-4 space-y-2">{invites.length===0?<p className="rounded-xl border p-5 text-center text-sm opacity-50">{t('access.noCodes')}</p>:invites.map(invite=><div key={invite.id} className="rounded-2xl border p-4"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl" style={{background:'var(--brand-subtle)',color:'var(--brand-primary)'}}><KeyRound size={17}/></div><div className="min-w-0 flex-1"><p className="font-mono text-sm font-semibold">{invite.code}</p><p className="mt-1 text-xs opacity-50">{invite.label||roleLabel(invite.role)} · {t('access.used')} {invite.use_count}{invite.max_uses?` ${t('access.of')} ${invite.max_uses}`:''}{invite.expires_at?` · ${t('access.expires')} ${new Date(invite.expires_at).toLocaleDateString(locale)}`:''}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${invite.active?'bg-green-100 text-green-700':'bg-gray-100 text-gray-600'}`}>{invite.active?t('access.active'):t('access.off')}</span></div><div className="mt-3 grid grid-cols-3 gap-2"><button onClick={()=>void copy(invite.code)} className="flex items-center justify-center gap-1 rounded-lg bg-black/5 py-2 text-xs"><Copy size={13}/>{t('access.copy')}</button><button onClick={()=>void toggleInvite(invite)} className="rounded-lg bg-black/5 py-2 text-xs">{invite.active?t('access.disable'):t('access.enable')}</button><button onClick={()=>void removeInvite(invite)} className="flex items-center justify-center gap-1 rounded-lg bg-red-50 py-2 text-xs text-red-700"><Trash2 size={13}/>{t('access.delete')}</button></div></div>)}</div></section>

    {error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-green-50 p-3 text-xs text-green-700">{message}</p>}
    {showCreate&&<div className="fixed inset-0 z-[140] flex items-end bg-black/45 sm:items-center sm:justify-center sm:p-4"><form onSubmit={createInvite} className="w-full max-w-lg rounded-t-3xl bg-white p-5 sm:rounded-3xl"><h3 className="font-serif text-xl">{t('access.newCodeTitle')}</h3><div className="mt-4 space-y-3"><input required className="w-full rounded-xl border p-3 font-mono text-sm uppercase" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input className="w-full rounded-xl border p-3 text-sm" placeholder={t('access.codeLabel')} value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/><select className="w-full rounded-xl border p-3 text-sm" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="member">{t('access.member')}</option><option value="resident">{t('access.resident')}</option><option value="volunteer">{t('access.volunteer')}</option><option value="staff">{t('access.staff')}</option><option value="board">{t('access.board')}</option></select><select className="w-full rounded-xl border p-3 text-sm" value={form.approval_mode} onChange={e=>setForm({...form,approval_mode:e.target.value})}><option value="inherit">{t('access.inherit')}</option><option value="automatic">{t('access.automatic')}</option><option value="manual">{t('access.manual')}</option></select><div className="grid grid-cols-2 gap-3"><input type="number" min="1" className="w-full rounded-xl border p-3 text-sm" placeholder={t('access.maxUses')} value={form.max_uses} onChange={e=>setForm({...form,max_uses:e.target.value})}/><input type="date" className="w-full rounded-xl border p-3 text-sm" value={form.expires_at} onChange={e=>setForm({...form,expires_at:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><button type="button" onClick={()=>setShowCreate(false)} className="rounded-xl border py-3 text-sm">{t('access.cancel')}</button><button disabled={saving} className="flex items-center justify-center gap-2 rounded-xl py-3 text-sm font-medium" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{saving?<Loader2 size={16} className="animate-spin"/>:<Users size={16}/>} {t('access.create')}</button></div></div></form></div>}
  </div>;
}
