import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Camera, CameraOff, CheckCircle2, ClipboardList, Download, Loader2, QrCode, RefreshCw, Search, UserCheck, Users, XCircle } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Activity={id:string;title:string;activity_date:string};
type Attendance={checkin_id:string;membership_id:string;member_number:string|null;full_name:string;email:string|null;checked_in_at:string;source:string};
type Registration={registration_id:string;full_name:string;email:string;phone:string|null;attendees:number;status:string;created_at:string;membership_id:string|null;member_number:string|null;checked_in:boolean;checked_in_at:string|null};
type Candidate={membership_id:string;full_name:string;member_number:string|null;email:string|null;status:string;already_checked_in:boolean};
type ScanResult={kind:'success'|'duplicate'|'error';message:string;memberNumber?:string};
type DetectorResult={rawValue?:string};
type Detector={detect:(source:CanvasImageSource)=>Promise<DetectorResult[]>};
type DetectorConstructor={new(options:{formats:string[]}):Detector};

const csvCell=(value:unknown)=>`"${String(value??'').replace(/"/g,'""')}"`;
const extractCardToken=(value:string,organizationId:string)=>{const raw=value.trim();const prefix=`yasaflow-member:${organizationId}:`;if(raw.startsWith(prefix))return raw.slice(prefix.length);if(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(raw))return raw;return null;};
const errorMessage=(message:string)=>message.includes('member_not_found')?'Medlemmet ble ikke funnet.':message.includes('member_not_active')?'Medlemskapet er ikke aktivt.':message.includes('not_authorized')?'Du har ikke tilgang til innsjekking.':'Innsjekkingen kunne ikke gjennomføres.';
const statusLabel=(status:string)=>status==='confirmed'?'Påmeldt':status==='waitlist'?'Venteliste':status==='cancelled'?'Avmeldt':status;
const statusClass=(status:string)=>status==='confirmed'?'bg-green-50 text-green-700':status==='waitlist'?'bg-amber-50 text-amber-700':status==='cancelled'?'bg-red-50 text-red-700':'bg-black/5';

export function ActivityAttendancePanel({organizationId,activity,onClose}:{organizationId:string;activity:Activity;onClose:()=>void}){
  const [attendance,setAttendance]=useState<Attendance[]>([]);const [registrations,setRegistrations]=useState<Registration[]>([]);const [loading,setLoading]=useState(true);const [code,setCode]=useState('');const [checking,setChecking]=useState(false);const [result,setResult]=useState<ScanResult|null>(null);const [cameraOn,setCameraOn]=useState(false);const [cameraError,setCameraError]=useState('');
  const [memberQuery,setMemberQuery]=useState('');const [candidates,setCandidates]=useState<Candidate[]>([]);const [searching,setSearching]=useState(false);const [manualBusy,setManualBusy]=useState('');
  const videoRef=useRef<HTMLVideoElement|null>(null);const streamRef=useRef<MediaStream|null>(null);const timerRef=useRef<number|null>(null);const busyRef=useRef(false);
  const loadData=async()=>{if(!supabase)return;setLoading(true);const [attendanceResult,registrationResult]=await Promise.all([supabase.rpc('get_activity_attendance',{p_activity_id:activity.id}),supabase.rpc('get_activity_registration_overview',{p_activity_id:activity.id})]);if(attendanceResult.error)setResult({kind:'error',message:attendanceResult.error.message});else setAttendance((attendanceResult.data||[]) as Attendance[]);if(registrationResult.error)setResult({kind:'error',message:registrationResult.error.message});else setRegistrations((registrationResult.data||[]) as Registration[]);setLoading(false);};
  useEffect(()=>{void loadData();return()=>stopCamera();},[activity.id]);
  useEffect(()=>{const timer=window.setTimeout(()=>void searchMembers(memberQuery),250);return()=>window.clearTimeout(timer);},[memberQuery,activity.id]);

  const searchMembers=async(query:string)=>{if(!supabase)return;setSearching(true);const {data,error}=await supabase.rpc('search_activity_checkin_members',{p_organization_id:organizationId,p_activity_id:activity.id,p_query:query});setSearching(false);if(error){setResult({kind:'error',message:error.message});return;}setCandidates((data||[]) as Candidate[]);};
  const checkIn=async(raw:string)=>{if(!supabase||busyRef.current)return;const token=extractCardToken(raw,organizationId);if(!token){setResult({kind:'error',message:'Ugyldig QR-kode. Bruk et Yasaflow-medlemskort.'});return;}busyRef.current=true;setChecking(true);setResult(null);const {data,error}=await supabase.rpc('check_in_member_by_card',{p_organization_id:organizationId,p_activity_id:activity.id,p_card_token:token});setChecking(false);busyRef.current=false;if(error){setResult({kind:'error',message:errorMessage(error.message)});return;}const payload=data as {status?:string;member_number?:string|null};if(payload.status==='already_checked_in')setResult({kind:'duplicate',message:'Medlemmet er allerede sjekket inn.',memberNumber:payload.member_number||undefined});else{setResult({kind:'success',message:'Innsjekking registrert.',memberNumber:payload.member_number||undefined});setCode('');await loadData();await searchMembers(memberQuery);}};
  const manualCheckIn=async(candidate:Candidate)=>{if(!supabase)return;setManualBusy(candidate.membership_id);setResult(null);const {data,error}=await supabase.rpc('check_in_member_manually',{p_organization_id:organizationId,p_activity_id:activity.id,p_membership_id:candidate.membership_id});setManualBusy('');if(error){setResult({kind:'error',message:errorMessage(error.message)});return;}const payload=data as {status?:string;member_number?:string|null};if(payload.status==='already_checked_in')setResult({kind:'duplicate',message:`${candidate.full_name} er allerede sjekket inn.`,memberNumber:payload.member_number||undefined});else{setResult({kind:'success',message:`${candidate.full_name} er sjekket inn.`,memberNumber:payload.member_number||undefined});await loadData();await searchMembers(memberQuery);}};
  const submit=(event:FormEvent)=>{event.preventDefault();void checkIn(code);};

  const stopCamera=()=>{if(timerRef.current)window.clearInterval(timerRef.current);timerRef.current=null;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setCameraOn(false);};
  const startCamera=async()=>{setCameraError('');const DetectorClass=(window as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;if(!DetectorClass){setCameraError('Kameraskanning støttes ikke i denne nettleseren. Bruk manuell kode eller Chrome på mobil.');return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}setCameraOn(true);const detector=new DetectorClass({formats:['qr_code']});timerRef.current=window.setInterval(async()=>{const video=videoRef.current;if(!video||video.readyState<2||busyRef.current)return;try{const found=await detector.detect(video);const value=found[0]?.rawValue;if(value){stopCamera();await checkIn(value);}}catch{/* keep scanning */}},500);}catch{setCameraError('Kamera kunne ikke åpnes. Kontroller kameratillatelsen.');stopCamera();}};
  const exportAttendance=()=>{const rows=[['Navn','Medlemsnummer','E-post','Innsjekket','Metode'],...attendance.map(row=>[row.full_name,row.member_number,row.email,new Date(row.checked_in_at).toLocaleString('nb-NO'),row.source])];downloadCsv(rows,`oppmote-${activity.title}`);};
  const exportRegistrations=()=>{const rows=[['Navn','E-post','Telefon','Antall','Status','Medlemsnummer','Sjekket inn','Påmeldt'],...registrations.map(row=>[row.full_name,row.email,row.phone,row.attendees,statusLabel(row.status),row.member_number,row.checked_in?'Ja':'Nei',new Date(row.created_at).toLocaleString('nb-NO')])];downloadCsv(rows,`pameldinger-${activity.title}`);};
  const downloadCsv=(rows:unknown[][],name:string)=>{const content='\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${name.toLowerCase().replace(/[^a-z0-9æøå]+/gi,'-')}.csv`;link.click();URL.revokeObjectURL(url);};
  const stats=useMemo(()=>({registered:registrations.filter(r=>r.status==='confirmed').reduce((sum,r)=>sum+r.attendees,0),waitlist:registrations.filter(r=>r.status==='waitlist').reduce((sum,r)=>sum+r.attendees,0),checkedIn:attendance.length}),[registrations,attendance]);

  return <div className="fixed inset-0 z-[150] overflow-y-auto bg-black/55 p-0 sm:p-4"><div className="mx-auto min-h-full w-full max-w-5xl bg-white p-5 sm:min-h-0 sm:rounded-3xl"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest opacity-45">Arrangement Pro</p><h3 className="font-serif text-2xl">Påmelding og innsjekk</h3><p className="mt-1 text-sm opacity-60">{activity.title} · {activity.activity_date}</p></div><button onClick={()=>{stopCamera();onClose();}} className="rounded-full bg-black/5 p-2" aria-label="Lukk"><XCircle size={20}/></button></div>
    <div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-black/[0.03] p-3 text-center"><p className="text-xl font-semibold">{stats.registered}</p><p className="text-[11px] opacity-50">Påmeldte</p></div><div className="rounded-2xl bg-black/[0.03] p-3 text-center"><p className="text-xl font-semibold">{stats.waitlist}</p><p className="text-[11px] opacity-50">Venteliste</p></div><div className="rounded-2xl bg-black/[0.03] p-3 text-center"><p className="text-xl font-semibold">{stats.checkedIn}</p><p className="text-[11px] opacity-50">Møtt</p></div></div>
    {result&&<div className={`mt-4 flex items-start gap-2 rounded-xl p-3 text-sm ${result.kind==='success'?'bg-green-50 text-green-800':result.kind==='duplicate'?'bg-amber-50 text-amber-800':'bg-red-50 text-red-800'}`}>{result.kind==='success'?<CheckCircle2 size={18}/>:<XCircle size={18}/>}<div><p className="font-semibold">{result.message}</p>{result.memberNumber&&<p className="text-xs opacity-70">Medlemsnummer: {result.memberNumber}</p>}</div></div>}
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border p-4"><div className="flex items-center gap-2"><QrCode size={18}/><h4 className="font-semibold">Skann medlemskort</h4></div><p className="mt-1 text-xs opacity-55">QR-koden inneholder bare organisasjon og medlemskortets sikre token.</p><div className="mt-4 overflow-hidden rounded-2xl bg-black"><video ref={videoRef} playsInline muted className={`aspect-video w-full object-cover ${cameraOn?'block':'hidden'}`}/>{!cameraOn&&<div className="flex aspect-video items-center justify-center text-white/55"><Camera size={42}/></div>}</div><button onClick={cameraOn?stopCamera:()=>void startCamera()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border py-3 text-sm font-semibold">{cameraOn?<><CameraOff size={17}/>Stopp kamera</>:<><Camera size={17}/>Åpne kamera</>}</button>{cameraError&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{cameraError}</p>}<form onSubmit={submit} className="mt-4"><label className="text-xs font-medium">Manuell QR-kode eller token<input value={code} onChange={e=>setCode(e.target.value)} className="mt-1 w-full rounded-xl border p-3 text-sm" placeholder="yasaflow-member:..."/></label><button disabled={checking||!code.trim()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold disabled:opacity-50" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{checking&&<Loader2 size={16} className="animate-spin"/>}Registrer innsjekk</button></form></section>
      <section className="rounded-2xl border p-4"><div className="flex items-center gap-2"><Search size={18}/><h4 className="font-semibold">Manuell innsjekk</h4></div><p className="mt-1 text-xs opacity-55">Søk etter navn, e-post eller medlemsnummer.</p><label className="mt-4 flex items-center gap-2 rounded-xl border px-3"><Search size={15} className="opacity-45"/><input value={memberQuery} onChange={e=>setMemberQuery(e.target.value)} className="w-full py-3 text-sm outline-none" placeholder="Søk medlem"/>{searching&&<Loader2 size={15} className="animate-spin"/>}</label><div className="mt-3 max-h-[360px] space-y-2 overflow-y-auto">{candidates.map(candidate=><article key={candidate.membership_id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{candidate.full_name}</p><p className="truncate text-xs opacity-50">{candidate.member_number||'Uten medlemsnummer'}{candidate.email?` · ${candidate.email}`:''}</p></div><button disabled={candidate.status!=='active'||candidate.already_checked_in||manualBusy===candidate.membership_id} onClick={()=>void manualCheckIn(candidate)} className="shrink-0 rounded-lg px-3 py-2 text-xs font-semibold disabled:opacity-45" style={{background:candidate.already_checked_in?'rgba(0,0,0,.05)':'var(--brand-primary)',color:candidate.already_checked_in?'inherit':'var(--brand-primary-text)'}}>{manualBusy===candidate.membership_id?<Loader2 size={14} className="animate-spin"/>:candidate.already_checked_in?'Sjekket inn':candidate.status!=='active'?'Inaktiv':'Sjekk inn'}</button></article>)}{!searching&&candidates.length===0&&<p className="rounded-xl bg-black/[0.03] p-5 text-center text-sm opacity-55">Ingen medlemmer funnet.</p>}</div></section></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><ClipboardList size={18}/><h4 className="font-semibold">Påmeldingsoversikt</h4><span className="rounded-full bg-black/5 px-2 py-0.5 text-xs">{registrations.length}</span></div><button onClick={exportRegistrations} disabled={!registrations.length} className="flex items-center gap-1 rounded-lg border px-2 py-2 text-xs disabled:opacity-40"><Download size={14}/>CSV</button></div>{loading?<div className="flex justify-center p-8"><Loader2 className="animate-spin"/></div>:registrations.length===0?<p className="mt-4 rounded-xl bg-black/[0.03] p-5 text-center text-sm opacity-55">Ingen påmeldinger ennå.</p>:<div className="mt-4 max-h-[520px] space-y-2 overflow-y-auto">{registrations.map(row=><article key={row.registration_id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold">{row.full_name}</p><span className={`rounded-full px-2 py-0.5 text-[10px] ${statusClass(row.status)}`}>{statusLabel(row.status)}</span>{row.checked_in&&<span className="rounded-full bg-blue-50 px-2 py-0.5 text-[10px] text-blue-700">Møtt</span>}</div><p className="truncate text-xs opacity-50">{row.email}{row.phone?` · ${row.phone}`:''}</p><p className="mt-1 text-[11px] opacity-45">{row.attendees} deltaker{row.attendees===1?'':'e'}{row.member_number?` · Medlem ${row.member_number}`:''}</p></div><span className="shrink-0 text-[10px] opacity-45">{new Date(row.created_at).toLocaleDateString('nb-NO')}</span></div></article>)}</div>}</section>
      <section className="rounded-2xl border p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><UserCheck size={18}/><h4 className="font-semibold">Oppmøteliste</h4><span className="rounded-full bg-black/5 px-2 py-0.5 text-xs">{attendance.length}</span></div><div className="flex gap-2"><button onClick={()=>void loadData()} className="rounded-lg border p-2" aria-label="Oppdater"><RefreshCw size={15}/></button><button onClick={exportAttendance} disabled={!attendance.length} className="flex items-center gap-1 rounded-lg border px-2 py-2 text-xs disabled:opacity-40"><Download size={14}/>CSV</button></div></div>{loading?<div className="flex justify-center p-8"><Loader2 className="animate-spin"/></div>:attendance.length===0?<p className="mt-4 rounded-xl bg-black/[0.03] p-5 text-center text-sm opacity-55">Ingen er sjekket inn ennå.</p>:<div className="mt-4 max-h-[520px] space-y-2 overflow-y-auto">{attendance.map(row=><article key={row.checkin_id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-semibold">{row.full_name}</p><p className="truncate text-xs opacity-50">{row.member_number||'Uten medlemsnummer'}{row.email?` · ${row.email}`:''}</p><p className="mt-1 text-[10px] uppercase tracking-wide opacity-40">{row.source==='manual'?'Manuell innsjekk':'QR-innsjekk'}</p></div><span className="shrink-0 text-[10px] opacity-45">{new Date(row.checked_in_at).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'})}</span></div></article>)}</div>}</section></div></div></div>;
}
