import { useEffect,useState } from 'react';
import { Check,Loader2,UserPlus,X } from 'lucide-react';
import { useAppI18n } from '../lib/appI18n';
import { getMembershipRequestTranslation } from '../lib/membershipRequestTranslations';
import { supabase } from '../lib/supabase';

type RequestRow={id:string;first_name:string;last_name:string;email:string;phone:string|null;birth_date:string|null;address:string|null;comment:string|null;status:'pending'|'approved'|'rejected';created_at:string};
export function MembershipRequestsModule({organizationId,onApproved}:{organizationId:string;onApproved?:()=>void}){
 const {language,locale}=useAppI18n();const t=(k:string)=>getMembershipRequestTranslation(language,k);
 const [rows,setRows]=useState<RequestRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');
 const load=async()=>{if(!supabase)return;setLoading(true);setError('');const {data,error}=await supabase.from('organization_membership_requests').select('*').eq('organization_id',organizationId).order('created_at',{ascending:false});if(error)setError(error.message);else setRows((data||[]) as RequestRow[]);setLoading(false);};
 useEffect(()=>{void load();},[organizationId,language]);
 const review=async(id:string,decision:'approved'|'rejected')=>{if(!supabase)return;setBusy(id);setError('');const {error}=await supabase.rpc('review_membership_request',{p_request_id:id,p_decision:decision});setBusy('');if(error){setError(error.message);return;}await load();if(decision==='approved')onApproved?.();};
 const pending=rows.filter(r=>r.status==='pending');
 return <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><UserPlus size={20} style={{color:'var(--brand-primary)'}}/><div><h3 className="font-serif text-xl">{t('membership.requests')}</h3><p className="text-sm opacity-55">{pending.length} {t('membership.pending').toLowerCase()}</p></div></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}{loading?<div className="flex justify-center p-6"><Loader2 className="animate-spin"/></div>:rows.length===0?<p className="mt-4 rounded-2xl border p-5 text-center text-sm opacity-50">{t('membership.noRequests')}</p>:<div className="mt-4 space-y-3">{rows.map(row=><article key={row.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="font-semibold">{row.first_name} {row.last_name}</h4><p className="mt-1 text-xs opacity-55">{row.email}{row.phone?` · ${row.phone}`:''}</p><p className="mt-1 text-[11px] opacity-40">{new Date(row.created_at).toLocaleDateString(locale)}</p></div><span className={`rounded-full px-2 py-1 text-[10px] ${row.status==='approved'?'bg-green-100 text-green-700':row.status==='rejected'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{t(`membership.${row.status}`)}</span></div>{(row.address||row.birth_date||row.comment)&&<div className="mt-3 rounded-xl bg-black/5 p-3 text-xs leading-5"><p>{row.birth_date||''}</p><p>{row.address||''}</p><p className="whitespace-pre-wrap">{row.comment||''}</p></div>}{row.status==='pending'&&<div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy===row.id} onClick={()=>void review(row.id,'rejected')} className="flex items-center justify-center gap-2 rounded-xl border py-2.5 text-sm font-semibold disabled:opacity-50"><X size={15}/>{t('membership.reject')}</button><button disabled={busy===row.id} onClick={()=>void review(row.id,'approved')} className="flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold disabled:opacity-50" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{busy===row.id?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>} {t('membership.approve')}</button></div>}</article>)}</div>}</section>;
}
