import { useEffect,useState } from 'react';
import { Loader2,Plus,Save,Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';

type CustomField={id:string;label:string;required:boolean;type:'text'|'textarea'};
export function MembershipFormSettings({organizationId}:{organizationId:string}){
 const [welcome,setWelcome]=useState('');const [fields,setFields]=useState<CustomField[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.from('organization_settings').select('membership_welcome_message,membership_custom_fields').eq('organization_id',organizationId).maybeSingle().then(({data,error})=>{if(error)setError(error.message);setWelcome(data?.membership_welcome_message||'');setFields(Array.isArray(data?.membership_custom_fields)?data.membership_custom_fields:[]);setLoading(false);});},[organizationId]);
 const addField=()=>setFields(previous=>[...previous,{id:`field_${Date.now()}`,label:'',required:false,type:'text'}]);
 const save=async()=>{if(!supabase)return;setSaving(true);setError('');setMessage('');const cleaned=fields.filter(field=>field.label.trim()).map(field=>({...field,label:field.label.trim()}));const {error}=await supabase.from('organization_settings').update({membership_welcome_message:welcome.trim()||null,membership_custom_fields:cleaned,updated_at:new Date().toISOString()}).eq('organization_id',organizationId);setSaving(false);if(error){setError(error.message);return;}setFields(cleaned);setMessage('Medlemsinnstillingene er lagret.');};
 if(loading)return <section className="rounded-3xl border bg-white p-5"><Loader2 className="animate-spin" size={18}/></section>;
 return <section className="rounded-3xl border bg-white p-5 shadow-sm"><h3 className="font-serif text-xl">Medlemsskjema og velkomst</h3><p className="mt-1 text-sm opacity-55">Tilpass velkomstmeldingen og feltene søkerne skal fylle ut.</p><label className="mt-4 block text-xs font-medium">Velkomstmelding ved godkjenning<textarea rows={4} className="mt-1 w-full rounded-xl border p-3 text-sm" value={welcome} onChange={e=>setWelcome(e.target.value)} placeholder="Velkommen som medlem..."/></label><div className="mt-5 flex items-center justify-between"><h4 className="text-sm font-semibold">Egendefinerte felt</h4><button type="button" onClick={addField} className="flex items-center gap-1 rounded-lg border px-3 py-2 text-xs"><Plus size={14}/>Legg til felt</button></div><div className="mt-3 space-y-2">{fields.map((field,index)=><div key={field.id} className="grid gap-2 rounded-xl border p-3 sm:grid-cols-[1fr_130px_auto_auto]"><input className="rounded-lg border px-3 py-2 text-sm" value={field.label} onChange={e=>setFields(fields.map((item,i)=>i===index?{...item,label:e.target.value}:item))} placeholder="Feltnavn"/><select className="rounded-lg border px-2 py-2 text-sm" value={field.type} onChange={e=>setFields(fields.map((item,i)=>i===index?{...item,type:e.target.value as 'text'|'textarea'}:item))}><option value="text">Kort tekst</option><option value="textarea">Lang tekst</option></select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={field.required} onChange={e=>setFields(fields.map((item,i)=>i===index?{...item,required:e.target.checked}:item))}/>Påkrevd</label><button type="button" aria-label="Slett felt" onClick={()=>setFields(fields.filter((_,i)=>i!==index))} className="rounded-lg p-2 text-red-600"><Trash2 size={16}/></button></div>)}</div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}{message&&<p className="mt-3 rounded-xl bg-green-50 p-3 text-xs text-green-700">{message}</p>}<button type="button" disabled={saving} onClick={()=>void save()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl py-3 text-sm font-semibold disabled:opacity-50" style={{background:'var(--brand-primary)',color:'var(--brand-primary-text)'}}>{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Lagre innstillinger</button></section>;
}
