import { useEffect, useState } from 'react';
import { X, Calendar, Clock, MapPin, User, Bell, Mail, MessageCircle, Phone } from 'lucide-react';
import type { SohbetItem } from '../types';
import { supabase } from '../lib/supabase';
import { useAppI18n } from '../lib/appI18n';

type ActivityWithContact = SohbetItem & { image_base64?:string; contactPersonId?:string };
type ContactPerson = {
  id:string; name:string; position:string; phone:string; email:string; whatsapp_number:string;
  bio:string; image_url:string; allow_call:boolean; allow_sms:boolean; allow_whatsapp:boolean; allow_email:boolean;
};

interface SohbetModalProps { item:ActivityWithContact|null; onClose:()=>void }
const brand={primary:'var(--brand-primary)',secondary:'var(--brand-secondary)',text:'var(--brand-text)',primaryText:'var(--brand-primary-text)'};
const mix=(color:string,amount:number,fallback='transparent')=>`color-mix(in srgb, ${color} ${amount}%, ${fallback})`;
const normalizePhone=(value:string)=>value.replace(/[^+\d]/g,'');
function escapeIcsText(value:string|undefined){return String(value||'').split('\\').join('\\\\').split('\n').join('\\n').split(',').join('\\,').split(';').join('\\;');}
function toIcsDate(date:string,time:string,addMinutes=0){const [hours='0',minutes='0']=(time||'00:00').split(':');const start=new Date(date);start.setHours(Number(hours),Number(minutes)+addMinutes,0,0);return start.toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';}
function downloadCalendarFile(item:SohbetItem,withReminder:boolean){const start=toIcsDate(item.date,item.time);const end=toIcsDate(item.date,item.time,120);const title=escapeIcsText(item.title);const description=escapeIcsText(item.description);const location=escapeIcsText(item.location);const fileName=`${item.title||'activity'}`.toLowerCase().replace(/[^a-z0-9æøåäöüß]+/gi,'-').replace(/^-+|-+$/g,'')||'activity';const alarm=withReminder?['BEGIN:VALARM','TRIGGER:-PT1H','ACTION:DISPLAY',`DESCRIPTION:${title}`,'END:VALARM']:[];const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Yasaflow//Activity//NO','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${item.id||Date.now()}@yasaflow.app`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').split('.')[0]}Z`,`DTSTART:${start}`,`DTEND:${end}`,`SUMMARY:${title}`,`DESCRIPTION:${description}`,`LOCATION:${location}`,...alarm,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`${fileName}${withReminder?'-reminder':''}.ics`;document.body.appendChild(link);link.click();document.body.removeChild(link);URL.revokeObjectURL(url);}
function openGoogleCalendar(item:SohbetItem){const start=toIcsDate(item.date,item.time);const end=toIcsDate(item.date,item.time,120);const url='https://calendar.google.com/calendar/render?action=TEMPLATE'+`&text=${encodeURIComponent(item.title||'Activity')}`+`&dates=${encodeURIComponent(`${start}/${end}`)}`+`&details=${encodeURIComponent(item.description||'')}`+`&location=${encodeURIComponent(item.location||'')}`;window.open(url,'_blank','noopener,noreferrer');}
function addToCalendar(item:SohbetItem,withReminder:boolean){if(/Android/i.test(navigator.userAgent))openGoogleCalendar(item);else downloadCalendarFile(item,withReminder);}

export function SohbetModal({item,onClose}:SohbetModalProps){
  const {t,locale,direction}=useAppI18n();
  const [contact,setContact]=useState<ContactPerson|null>(null);
  useEffect(()=>{const client=supabase;if(!client||!item?.contactPersonId){setContact(null);return;}let cancelled=false;void client.from('organization_staff').select('id,name,position,phone,email,whatsapp_number,bio,image_url,allow_call,allow_sms,allow_whatsapp,allow_email').eq('id',item.contactPersonId).eq('active',true).eq('public_visible',true).maybeSingle().then(({data})=>{if(!cancelled)setContact((data||null) as ContactPerson|null);});return()=>{cancelled=true;};},[item?.contactPersonId]);
  if(!item)return null;
  const formattedDate=new Date(item.date).toLocaleDateString(locale,{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  const imageSrc=item.imageBase64||item.image_base64;
  const phone=normalizePhone(contact?.phone||'');
  const whatsapp=normalizePhone(contact?.whatsapp_number||contact?.phone||'');
  return <div className="fixed inset-0 z-[90] flex items-start justify-center p-0 sm:p-4 sm:py-8" dir={direction}>
    <div className="absolute inset-0 backdrop-blur-sm" style={{backgroundColor:mix(brand.secondary,70)}} onClick={onClose}/>
    <div className="theme-surface relative flex max-h-screen w-full max-w-2xl flex-col overflow-hidden rounded-none border-2 shadow-2xl sm:max-h-[calc(100vh-4rem)] sm:rounded-2xl">
      <div className="theme-surface sticky top-0 z-10 flex items-center justify-between border-b-2 px-5 py-4"><span className="rounded px-2 py-1 text-xs font-semibold uppercase tracking-wider" style={{backgroundColor:'var(--brand-subtle)',color:brand.primary}}>{t('activity.label')}</span><button onClick={onClose} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full" style={{backgroundColor:'var(--brand-subtle)',color:mix(brand.text,65)}} aria-label={t('common.close')}><X size={20}/></button></div>
      <div className="flex-1 overflow-y-auto">{imageSrc&&<img src={imageSrc} alt={item.title} className="block h-auto w-full object-contain"/>}<div className="p-5 sm:p-6"><h2 className="mb-4 font-serif text-xl leading-tight sm:text-2xl">{item.title}</h2><div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-2">{item.date&&<div className="theme-card theme-muted flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Calendar size={15} style={{color:brand.primary}}/><span className="capitalize">{formattedDate}</span></div>}{item.time&&<div className="theme-card theme-muted flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><Clock size={15} style={{color:brand.primary}}/><span>{item.time}</span></div>}{item.location&&<div className="theme-card theme-muted flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><MapPin size={15} style={{color:brand.primary}}/><span>{item.location}</span></div>}</div>
      {item.description&&<div className="prose prose-sm mb-6 max-w-none"><p className="whitespace-pre-wrap leading-relaxed opacity-80" style={{color:brand.text}}>{item.description}</p></div>}
      {contact&&<section className="mb-6 rounded-2xl border p-4" style={{borderColor:'var(--brand-border)',backgroundColor:'var(--brand-card)'}}><p className="text-xs font-semibold uppercase tracking-wider opacity-45">{t('activity.contact')}</p><div className="mt-3 flex items-start gap-3">{contact.image_url?<img src={contact.image_url} alt="" className="h-14 w-14 rounded-full object-cover"/>:<span className="flex h-14 w-14 items-center justify-center rounded-full" style={{background:'var(--brand-subtle)',color:brand.primary}}><User size={22}/></span>}<div className="min-w-0 flex-1"><h3 className="font-semibold">{contact.name}</h3>{contact.position&&<p className="text-sm opacity-55">{contact.position}</p>}{contact.bio&&<p className="mt-2 text-sm leading-5 opacity-70">{contact.bio}</p>}</div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{contact.allow_call&&phone&&<a href={`tel:${phone}`} className="flex items-center justify-center gap-1 rounded-xl border py-2.5 text-xs font-semibold"><Phone size={15}/>{t('activity.call')}</a>}{contact.allow_sms&&phone&&<a href={`sms:${phone}`} className="flex items-center justify-center gap-1 rounded-xl border py-2.5 text-xs font-semibold"><MessageCircle size={15}/>{t('activity.sms')}</a>}{contact.allow_whatsapp&&whatsapp&&<a href={`https://wa.me/${whatsapp.replace(/^\+/,'')}`} target="_blank" rel="noreferrer" className="flex items-center justify-center gap-1 rounded-xl border py-2.5 text-xs font-semibold"><MessageCircle size={15}/>{t('activity.whatsapp')}</a>}{contact.allow_email&&contact.email&&<a href={`mailto:${contact.email}`} className="flex items-center justify-center gap-1 rounded-xl border py-2.5 text-xs font-semibold"><Mail size={15}/>{t('activity.email')}</a>}</div></section>}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><button type="button" onClick={()=>addToCalendar(item,false)} className="theme-card flex w-full items-center justify-center gap-2 rounded-xl border-2 py-3.5 text-sm font-semibold shadow-sm"><Calendar size={18} style={{color:brand.primary}}/>{t('activity.addCalendar')}</button><button type="button" onClick={()=>addToCalendar(item,true)} className="theme-primary-button flex w-full items-center justify-center gap-2 rounded-xl py-3.5 text-sm font-semibold shadow-sm"><Bell size={18}/>{t('activity.addReminder')}</button></div>
      </div></div>
    </div>
  </div>;
}
