create extension if not exists pgcrypto;

create table if not exists public.public_api_abuse_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  organization_id text,
  subject_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists public_api_abuse_events_lookup_idx
  on public.public_api_abuse_events (event_type, organization_id, subject_hash, created_at desc);

alter table public.public_api_abuse_events enable row level security;
revoke all on table public.public_api_abuse_events from public, anon, authenticated;
grant all on table public.public_api_abuse_events to service_role;
revoke all on sequence public.public_api_abuse_events_id_seq from public, anon, authenticated;
grant all on sequence public.public_api_abuse_events_id_seq to service_role;

create or replace function public.log_public_abuse_event(
  p_event_type text,
  p_organization_id text,
  p_subject text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
begin
  insert into public.public_api_abuse_events(event_type, organization_id, subject_hash, metadata)
  values (
    left(coalesce(p_event_type, 'unknown'), 100),
    nullif(left(coalesce(p_organization_id, ''), 100), ''),
    case
      when nullif(trim(coalesce(p_subject, '')), '') is null then null
      else encode(digest(lower(trim(p_subject)), 'sha256'), 'hex')
    end,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$function$;

create or replace function public.enforce_public_rate_limit(
  p_event_type text,
  p_organization_id text,
  p_subject text,
  p_window interval,
  p_limit integer
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_hash text;
  v_count integer;
begin
  if p_limit < 1 then raise exception 'invalid_rate_limit'; end if;
  v_hash := encode(digest(lower(trim(coalesce(p_subject,''))), 'sha256'), 'hex');

  select count(*) into v_count
  from public.public_api_abuse_events
  where event_type = p_event_type
    and organization_id is not distinct from p_organization_id
    and subject_hash = v_hash
    and created_at >= now() - p_window;

  if v_count >= p_limit then
    perform public.log_public_abuse_event(
      p_event_type || '_blocked',
      p_organization_id,
      p_subject,
      jsonb_build_object('window', p_window::text, 'limit', p_limit)
    );
    raise exception 'rate_limited';
  end if;

  perform public.log_public_abuse_event(p_event_type, p_organization_id, p_subject, '{}'::jsonb);
end;
$function$;

revoke all on function public.log_public_abuse_event(text,text,text,jsonb) from public, anon, authenticated;
revoke all on function public.enforce_public_rate_limit(text,text,text,interval,integer) from public, anon, authenticated;
grant execute on function public.log_public_abuse_event(text,text,text,jsonb) to service_role;
grant execute on function public.enforce_public_rate_limit(text,text,text,interval,integer) to service_role;

create or replace function public.register_for_activity(
  p_activity_id uuid,
  p_full_name text,
  p_email text,
  p_phone text default null,
  p_attendees integer default 1,
  p_payment_confirmed boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_activity public.organization_activities%rowtype;
  v_registered integer;
  v_status text := 'confirmed';
  v_registration public.activity_registrations%rowtype;
  v_email text := lower(trim(coalesce(p_email,'')));
begin
  if length(trim(coalesce(p_full_name,''))) < 2 then raise exception 'Name is required'; end if;
  if length(trim(p_full_name)) > 200 then raise exception 'name_too_long'; end if;
  if length(v_email) > 254 or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'Valid email is required'; end if;
  if p_phone is not null and length(trim(p_phone)) > 40 then raise exception 'phone_too_long'; end if;
  if p_attendees < 1 or p_attendees > 20 then raise exception 'Invalid attendee count'; end if;

  select * into v_activity
  from public.organization_activities
  where id=p_activity_id and status='published' and visibility='public';
  if not found then raise exception 'Activity not found'; end if;

  perform public.enforce_public_rate_limit('activity_registration', v_activity.organization_id, v_email, interval '10 minutes', 5);

  if not v_activity.registration_enabled then raise exception 'Registration is not enabled'; end if;
  if v_activity.registration_deadline is not null and now()>v_activity.registration_deadline then raise exception 'Registration deadline has passed'; end if;
  if coalesce(v_activity.payment_required,false) and coalesce(v_activity.payment_confirmation_required,true) and not p_payment_confirmed then raise exception 'Payment confirmation is required'; end if;

  select coalesce(sum(attendees),0) into v_registered
  from public.activity_registrations
  where activity_id=p_activity_id and status='confirmed';

  if v_activity.capacity is not null and v_registered+p_attendees>v_activity.capacity then v_status:='waitlist'; end if;

  insert into public.activity_registrations(organization_id,activity_id,full_name,email,phone,attendees,status,payment_confirmed)
  values(v_activity.organization_id,p_activity_id,trim(p_full_name),v_email,nullif(trim(p_phone),''),p_attendees,v_status,coalesce(p_payment_confirmed,false))
  on conflict(activity_id,email) do update
  set full_name=excluded.full_name,
      phone=excluded.phone,
      attendees=excluded.attendees,
      status=excluded.status,
      payment_confirmed=excluded.payment_confirmed,
      updated_at=now()
  returning * into v_registration;

  return jsonb_build_object('registration_id',v_registration.id,'status',v_status,'ticket_token',v_registration.ticket_token);
end;
$function$;

create or replace function public.submit_membership_request_v2(
  p_organization_id text,
  p_first_name text,
  p_last_name text,
  p_email text,
  p_phone text default null,
  p_birth_date date default null,
  p_address text default null,
  p_comment text default null,
  p_custom_answers jsonb default '{}'::jsonb,
  p_invitation_code text default null
)
returns table(request_id uuid, event_type text, membership_status text)
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  v_mode text;
  v_open boolean;
  v_request_id uuid;
  v_person_id uuid;
  v_code_id uuid;
  v_email text:=lower(trim(p_email));
begin
  if nullif(trim(p_first_name),'') is null or nullif(trim(p_last_name),'') is null or nullif(v_email,'') is null then raise exception 'required_fields_missing'; end if;
  if length(trim(p_first_name))>100 or length(trim(p_last_name))>100 then raise exception 'name_too_long'; end if;
  if length(v_email)>254 or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'invalid_email'; end if;
  if p_phone is not null and length(trim(p_phone))>40 then raise exception 'phone_too_long'; end if;
  if p_address is not null and length(trim(p_address))>500 then raise exception 'address_too_long'; end if;
  if p_comment is not null and length(trim(p_comment))>4000 then raise exception 'comment_too_long'; end if;
  if p_birth_date is not null and (p_birth_date>current_date or p_birth_date<current_date-interval '120 years') then raise exception 'invalid_birth_date'; end if;
  if jsonb_typeof(coalesce(p_custom_answers,'{}'::jsonb))<>'object' or octet_length(coalesce(p_custom_answers,'{}'::jsonb)::text)>32768 then raise exception 'invalid_custom_answers'; end if;
  if p_invitation_code is not null and length(trim(p_invitation_code))>128 then raise exception 'invalid_invitation_code'; end if;
  if not exists(select 1 from public.organizations where id=p_organization_id) then raise exception 'organization_not_found'; end if;

  perform public.enforce_public_rate_limit('membership_request', p_organization_id, v_email, interval '1 hour', 3);

  if exists(
    select 1 from public.organization_membership_requests
    where organization_id=p_organization_id and lower(email)=v_email and created_at>=now()-interval '15 minutes'
  ) then
    perform public.log_public_abuse_event('membership_duplicate_blocked',p_organization_id,v_email,'{}'::jsonb);
    raise exception 'duplicate_request_recently_submitted';
  end if;

  if not exists (
    select 1 from public.organization_modules m
    where m.organization_id=p_organization_id and m.module_id='members' and m.enabled=true
  ) then raise exception 'members_module_disabled'; end if;

  select coalesce(s.membership_join_mode,'manual'),coalesce(s.membership_registration_open,true)
  into v_mode,v_open
  from public.organization_settings s
  where s.organization_id=p_organization_id;
  if not found then v_mode:='manual';v_open:=true;end if;
  if not v_open then raise exception 'membership_registration_closed'; end if;
  if exists (
    select 1 from public.organization_memberships m
    where m.organization_id=p_organization_id and lower(coalesce(m.email,''))=v_email and m.status='active'
  ) then raise exception 'already_active_member'; end if;

  if v_mode='invitation' then
    perform public.enforce_public_rate_limit('membership_invitation_attempt', p_organization_id, v_email, interval '15 minutes', 10);
    select c.id into v_code_id
    from public.organization_membership_invitation_codes c
    where c.organization_id=p_organization_id
      and upper(c.code)=upper(trim(coalesce(p_invitation_code,'')))
      and c.active=true
      and (c.valid_from is null or c.valid_from<=now())
      and (c.valid_until is null or c.valid_until>=now())
      and (c.max_uses is null or c.use_count<c.max_uses)
    for update;
    if v_code_id is null then
      perform public.log_public_abuse_event(
        'membership_invitation_invalid',
        p_organization_id,
        v_email,
        jsonb_build_object('code_length',length(trim(coalesce(p_invitation_code,''))))
      );
      raise exception 'invalid_invitation_code';
    end if;
  end if;

  insert into public.organization_membership_requests(organization_id,first_name,last_name,email,phone,birth_date,address,comment,custom_answers,status,reviewed_at,updated_at)
  values(p_organization_id,trim(p_first_name),trim(p_last_name),v_email,nullif(trim(p_phone),''),p_birth_date,nullif(trim(p_address),''),nullif(trim(p_comment),''),coalesce(p_custom_answers,'{}'::jsonb),case when v_mode='manual' then 'pending' else 'approved' end,case when v_mode='manual' then null else now() end,now())
  returning id into v_request_id;

  if v_mode='manual' then
    insert into public.membership_email_jobs(request_id,event_type) values(v_request_id,'received') on conflict do nothing;
    return query select v_request_id,'received'::text,'pending'::text;
    return;
  end if;

  insert into public.people(full_name,primary_email,primary_phone,updated_at)
  values(trim(p_first_name)||' '||trim(p_last_name),v_email,nullif(trim(p_phone),''),now())
  returning id into v_person_id;

  insert into public.organization_memberships(organization_id,person_id,email,phone,address,join_date,status,internal_notes,updated_at)
  values(p_organization_id,v_person_id,v_email,nullif(trim(p_phone),''),nullif(trim(p_address),''),current_date,'active',nullif(trim(p_comment),''),now());

  if v_code_id is not null then
    update public.organization_membership_invitation_codes
    set use_count=use_count+1,updated_at=now()
    where id=v_code_id;
  end if;

  insert into public.membership_email_jobs(request_id,event_type) values(v_request_id,'approved') on conflict do nothing;
  return query select v_request_id,'approved'::text,'active'::text;
end;
$function$;

revoke all on function public.register_for_activity(uuid,text,text,text,integer,boolean) from public;
revoke all on function public.submit_membership_request_v2(text,text,text,text,text,date,text,text,jsonb,text) from public;
grant execute on function public.register_for_activity(uuid,text,text,text,integer,boolean) to anon, authenticated, service_role;
grant execute on function public.submit_membership_request_v2(text,text,text,text,text,date,text,text,jsonb,text) to anon, authenticated, service_role;
